#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TUNNEL_NAME="${TUNNEL_NAME:-aio-tunnel}"
WEB_HOST="${WEB_HOST:-}"
GAME_HOST="${GAME_HOST:-}"
LOGIN="${LOGIN:-0}"
APPLY_DNS="${APPLY_DNS:-0}"
need(){ command -v "$1" >/dev/null || return 1; }
if ! need cloudflared; then
  echo '[cloudflared] installing latest Linux amd64 binary'
  curl -fL --retry 3 https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o /tmp/cloudflared
  sudo install -m 0755 /tmp/cloudflared /usr/local/bin/cloudflared
fi
if [[ "$LOGIN" == 1 ]]; then
  echo '[cloudflared] opening Cloudflare login; complete the browser step, then rerun this script'
  cloudflared tunnel login
fi
if [[ -z "$WEB_HOST" || -z "$GAME_HOST" ]]; then
  echo "Usage: WEB_HOST=play.example.com GAME_HOST=game.example.com TUNNEL_NAME=$TUNNEL_NAME $0"
  echo 'Set LOGIN=1 once if cloudflared tunnel login has not been completed.'
  exit 2
fi
TUNNEL_JSON="$(cloudflared tunnel list --output json 2>/dev/null || true)"
TUNNEL_ID="$(printf '%s' "$TUNNEL_JSON" | python3 -c 'import json,sys; name=sys.argv[1]; data=json.load(sys.stdin); print(next((x.get("id", "") for x in data if x.get("name") == name), ""))' "$TUNNEL_NAME" 2>/dev/null || true)"
if [[ -z "$TUNNEL_ID" ]]; then
  echo "[cloudflared] tunnel $TUNNEL_NAME was not found. Create it with: cloudflared tunnel create $TUNNEL_NAME"
  exit 1
fi
CRED="$HOME/.cloudflared/$TUNNEL_ID.json"
[[ -f "$CRED" ]] || { echo "Missing credentials file $CRED" >&2; exit 1; }
mkdir -p "$ROOT/cloudflared"
cat > "$ROOT/cloudflared/config.yml" <<EOF
# Generated by setup-cloudflared.sh for Bellascape.
tunnel: $TUNNEL_ID
credentials-file: $CRED
ingress:
  - hostname: $WEB_HOST
    service: http://127.0.0.1:3000
  - hostname: $GAME_HOST
    service: http://127.0.0.1:43594
  - service: http_status:404
EOF
printf '\n[cloudflared] generated %s\n' "$ROOT/cloudflared/config.yml"
echo "Before public DNS, test locally with: ./scripts/test-cloudflared.sh"
echo "When ready, route DNS with: cloudflared tunnel route dns $TUNNEL_NAME $WEB_HOST"
echo "Then route the game hostname with: cloudflared tunnel route dns $TUNNEL_NAME $GAME_HOST"
if [[ "$APPLY_DNS" == 1 ]]; then
  cloudflared tunnel route dns "$TUNNEL_NAME" "$WEB_HOST"
  cloudflared tunnel route dns "$TUNNEL_NAME" "$GAME_HOST"
  echo '[cloudflared] DNS routes applied.'
else
  echo '[cloudflared] DNS not changed. Set APPLY_DNS=1 only after reviewing the hostnames.'
fi
